version: "3.8"
services:
    bot:
        image: telegram-passgen-bot:latest
        container_name: "tg-passgen-bot"
        volumes:
            - './data:/app/data'
        restart: unless-stopped
